<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation;
use Magento\Catalog\Model\Category;

/** @var Navigation $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

// Fetch current category and its subcategories
/** @var Category $currentCategory */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currentCategory = $objectManager->get('Magento\Framework\Registry')->registry('current_category');

$subcategories = [];

if ($currentCategory->getId()) {
    /** @var CategoryRepository $categoryRepository */
    /** @var \Magento\Framework\View\Element\Template $block */

    try {
        $categoryRepository = $objectManager->get('Magento\Catalog\Model\CategoryRepository');
        $categoryIds = explode(',', $categoryRepository->get($currentCategory->getId())->getChildren());
        foreach ($categoryIds as $categoryId) {
            try {
                $category = $categoryRepository->get($categoryId);
                $subcategories[] = $category;
            } catch (\Magento\Framework\Exception\NoSuchEntityException $e) {
                // Handle non-existent category
                continue;
            }
        }
    } catch (\Exception $e) {
        echo 'Error fetching categories: ' . $e->getMessage();
    }
}
?>

<?php if ($subcategories): ?>
    <div class="subcategory-slider mt-6">
        <div class="owl-carousel owl-theme">
            <?php foreach ($subcategories as $subcategory): ?>
                <?php if ($subcategory->getIsActive()): ?>
                    <div class="item flex flex-row justify-center items-center w-64 min-h-[184px] p-4 mx-auto md:mx-0 border border-container-lighter rounded">
                        <a href="<?= $subcategory->getUrl() ?>" class="flex justify-center items-center space-x-4">
                            <img
                                src="<?= $subcategory->getImageUrl() ?>"
                                alt="<?= $escaper->escapeHtml($subcategory->getName()) ?>"
                                class="h-auto object-cover rounded" style="width: 5rem !important;"
                            >
                            <span class="block text-lg font-sm text-primary">
                                <?= $escaper->escapeHtml($subcategory->getName()) ?>
                            </span>
                        </a>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>


<?php if ($block->canShowBlock()): ?>
    <div
        x-data="initLayeredNavigation()"
        x-init="checkIsMobileResolution()"
        @resize.window.debounce="checkIsMobileResolution()"
        @visibilitychange.window.debounce="checkIsMobileResolution()"
        class="block border border-container bg-container-darker p-4 md:border-0 md:bg-transparent md:py-0 md:px-0 my-6"
        role="region"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Product filters')) ?>"
    >
        <h2
            id="filters-heading"
            class="block-title"
        >
            <button
                type="button"
                @click="blockOpen = !blockOpen"
                class="block-title flex items-center justify-between w-full text-start"
                aria-controls="filters-content"
                :aria-expanded="blockOpen"
                :aria-disabled="!isMobile"
                :disabled="!isMobile ? '' : null"
            >
                <span class="text-primary text-md md:text-3xl font-medium uppercase">
                    <?= $escaper->escapeHtml(__('Shop By')) ?>
                </span>
                <span
                    class="py-1 px-1 bg-container-lighter rounded border border-container-darker md:hidden"
                    x-ref="LayeredNavigationMobileToggleIcon"
                >
                    <?= $heroicons->chevronDownHtml(
                        'transition-transform transform duration-300 ease-in-out',
                        24,
                        24,
                        [
                            ":class" => "{ 'rotate-180': blockOpen }",
                            "aria-hidden" => "true",
                            "focusable" => "false"
                        ]
                    ); ?>
                </span>
            </button>
        </h2>
        <div
            id="filters-content"
            class="block-content filter-content md:block pt-4"
            :class="{ 'hidden': !blockOpen }"
        >
            <?= $block->getChildHtml('state') ?>
            <a
                href="#product-list"
                class="sr-only focus:not-sr-only bg-blue-600 text-white px-12 py-4 text-center block rounded-sm"
            >
                <?= $escaper->escapeHtml(__('Skip to product list')) ?>
            </a>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <div
                        x-data="{
                            open: false,
                            id: $id('filter-option')
                        }"
                        x-defer="intersect"
                        class="filter-option card my-4 py-0 px-2"
                        style="margin-left: 0;"
                    >
                        <h3 :id="`${id}-title`">
                            <button
                                type="button"
                                @click="open = !open"
                                class="filter-options-title flex justify-between items-center cursor-pointer text-start hover:text-secondary-darker border-container w-full"
                                :class="{ 'border-b pb-4': open }"
                                :aria-controls="`${id}-content`"
                                :aria-expanded="open"
                            >
                                <span class="title text-md md:text-lg">
                                    <?= $escaper->escapeHtml(__($filter->getName())) ?>
                                    <span class="sr-only"> <?= $escaper->escapeHtml(__('filter')) ?></span>
                                </span>
                                <span class="py-1 px-1 rounded border-container">
                                    <?= $heroicons->chevronDownHtml(
                                        'transition-transform transform duration-300 ease-in-out',
                                        24,
                                        24,
                                        [
                                            ":class" => "{ 'rotate-180': open }",
                                            "aria-hidden" => "true",
                                            "focusable" => "false"
                                        ]
                                    ); ?>
                                </span>
                            </button>
                        </h3>
                        <template x-if="open">
                            <div
                                :id="`${id}-content`"
                                class="filter-options-content pt-3"
                            >
                                <?= /* @noEscape */ $block->getChildBlock('renderer')->setFilterTitle($filter->getName())->render($filter); ?>
                            </div>
                        </template>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <script>
        function initLayeredNavigation() {
            return {
                isMobile: false,
                blockOpen: false,
                checkIsMobileResolution() {
                    const mobileElement = this.$refs.LayeredNavigationMobileToggleIcon;
                    this.isMobile = mobileElement
                        ? getComputedStyle(mobileElement).display !== "none"
                        : window.matchMedia('(max-width: 767px)').matches; // Fallback to `md` breakpoint
                }
            }
        }
    </script>
    <script>
        // Use Promise.all to load jQuery and Owl Carousel before initializing the carousel
        Promise.all([
            loadScript("https://code.jquery.com/jquery-3.6.0.min.js"),
            loadScript("https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js")
        ])
            .then(() => {
                // Now that both scripts are loaded, initialize Owl Carousel
                jQuery(document).ready(function($){
                    $(".owl-carousel").owlCarousel({
                        loop: false,
                        margin: 10,
                        nav: false,
                        dots: true,
                        responsive: {
                            0: { items: 1 },
                            600: { items: 2 },
                            1000: { items: 4 },
                            1280: {items: 5}
                        }
                    });
                });
            })
            .catch(err => console.error("Error loading scripts:", err));

    </script>

<?php endif; ?>

<style>
    @media screen and (max-width: 767px) {
        .mst-nav__horizontal-bar .block-content {
            flex-wrap: unset !important;
            flex-direction: column;
        }
    }
</style>
